#!/bin/bash

echo "==================================="
echo "Studio Portal Vercel Deployment"
echo "==================================="
echo ""
echo "This script will help you deploy the studio portal to Vercel."
echo ""
echo "Prerequisites:"
echo "1. You need a Vercel account (sign up at https://vercel.com)"
echo "2. The project must be connected to your GitHub repository"
echo ""
echo "Steps to deploy:"
echo ""
echo "1. First, login to Vercel CLI:"
echo "   npx vercel login"
echo ""
echo "2. Link this project to Vercel:"
echo "   npx vercel link"
echo "   - Choose your scope/team"
echo "   - Link to existing project or create new"
echo "   - Set project name: hobbyist-partner-portal"
echo ""
echo "3. Deploy to production:"
echo "   npx vercel --prod"
echo ""
echo "4. Or use the Vercel Dashboard:"
echo "   - Go to https://vercel.com/new"
echo "   - Import from GitHub: Chromeox/hobbyist-web-partner-v2"
echo "   - Root directory: web-partner"
echo "   - Framework: Next.js"
echo "   - Build command: npm run build"
echo "   - Output directory: .next"
echo ""
echo "Environment Variables needed in Vercel:"
echo "- NEXT_PUBLIC_SUPABASE_URL"
echo "- NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "- SUPABASE_SERVICE_ROLE_KEY"
echo "- NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "- STRIPE_SECRET_KEY"
echo "- STRIPE_WEBHOOK_SECRET"
echo "- NEXTAUTH_URL (your production URL)"
echo "- NEXTAUTH_SECRET (generate with: openssl rand -base64 32)"
echo ""
echo "==================================="
echo "Ready to deploy? Run the commands above!"